config/routes.rb
Rails.application.routes.draw do
  root to: 'users#show'

  get    '/login', to: 'sessions#new'
  delete '/login', to: 'sessions#destroy', as: 'logout'

  get '/auth/facebook', as: 'facebook_login'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  namespace :admin do
    resources :uploads, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :products, dependent: :destroy

  def self.import(customers)
    customers.map do |customer|
      create(id:              customer[:CustomerID],
             first_name:      customer[:FirstName],
             last_name:       customer[:LastName],
             account_balance: customer[:AccountBalance],
             active_items:    customer[:ActiveItems])
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :customer

  def self.import(products)
    products.map do |product|
      create(id:             product[:ProductID],   customer_id: product[:CustomerID],
             product_type:   product[:ProductType], color:       product[:ProductColor],
             size:           product[:ProductSize], description: product[:ProductDescription],
             original_price: product[:OrigPrice],   price:       product[:Price],
             enter_date:     product[:EnterDate],   expire_date: product[:ExpireDate],
             item_count:     product[:ItemCount])
    end
  end
end

app/models/upload.rb
class Upload < ApplicationRecord
  def self.import(consign_mdb)
    ActiveRecord::Base.transaction do
      transaction_records = []

      transaction_records << Customer.destroy_all
      transaction_records << Product.destroy_all

      transaction_records << Customer.import(consign_mdb[:Customers])
      transaction_records << Product.import(consign_mdb[:Merchandise])

      @errors = transaction_records.flatten.map do |record|
        record.errors.full_messages
      end.uniq.flatten
      raise ActiveRecord::Rollback unless @errors.empty?
    end

    @errors
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_oauth(oauth_info)
    current_user = find_or_create_by(uid: oauth_info[:uid]) do |user|
      user.provider = oauth_info[:provider]
      user.name = oauth_info[:info][:name]
      user.oauth_token = oauth_info[:credentials][:token]
      user.oauth_token_expires_at = Time.at(oauth_info[:credentials][:expires_at])
    end
    current_user.update(admin: admin?(oauth_info[:uid]))
    current_user
  end

  def self.admin?(uid)
    ENV.fetch('ADMINS').split(',').include?(uid)
  end
end

app/controllers/admin/uploads_controller.rb
module Admin
  class UploadsController < ApplicationController
    before_action :authorize!

    def new; end

    def create
      consign_mdb = Mdb.open(params[:upload].tempfile)
      errors = Upload.import(consign_mdb)
      if errors.empty?
        flash[:notice] = "Success! You're the best!"
      else
        flash[:alert] = 'ERROR: Records not successfully imported'
      end
      redirect_to action: 'new'
    end

    private

    def authorize!
      raise(ActionController::RoutingError, 'Not Found') unless admin?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin?
    current_user&.admin?
  end

  private

  before_action :authenticate!

  def authenticate!
    is_login_path = params[:controller] == 'sessions' &&
                    params[:action].in?(%w[new create failure])
    return if current_user || is_login_path
    redirect_to login_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_or_create_from_oauth(oauth_info)
    session[:user_id] = user.id
    redirect_to '/', notice: 'Login Successful'
  end

  def failure
    redirect_to login_path, notice: 'Login Unsuccessful'
  end

  def destroy
    reset_session
    redirect_to login_path, notice: 'Logout Successful'
  end

  private

  def oauth_info
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    if @user.myresaleweb_id && @user.myresaleweb_last_name

    else
      redirect_to('/credentials')
    end
  end

  def new
    @user = current_user
  end

  def create
    current_user.update(
      myresaleweb_id: params[:user][:myresaleweb_id],
      myresaleweb_last_name: params[:user][:myresaleweb_last_name]
    )

    redirect_to(root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/uploads/new.html.erb
<%= form_tag({action: :create}, multipart: true) do %>
  <%= label_tag(:upload, "Upload consign.mdb file:") %>
  <%= file_field_tag :upload %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IconocladMyResaleWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flash-messages">
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
        <hr />
      <% end -%>
    </div>

    <div>
      <% if current_user %>
        Logged in as <%= current_user.name %> |
        <%= link_to "Log Out", logout_path, method: :delete %>
      <% else %>
        <%= link_to "Log in with Facebook", facebook_login_path %>
      <% end %>
      <hr>
      <%= link_to 'Admin Dashboard', new_admin_upload_path if admin? %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user, url: {action: "create"}, html: {class: "nifty_form", method: "post"} do |f| %>
  <%= f.label 'ID' %>
  <%= f.text_field :myresaleweb_id %><br />

  <%= f.label 'Last Name' %>
  <%= f.text_field :myresaleweb_last_name %><br />

  <%= f.submit "Submit" %>
<% end %>